# Generated by Django 3.2.5 on 2021-08-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='member',
            field=models.IntegerField(default=0),
        ),
    ]
